#! /bin/bash

function build-docker() {
    docker build -f docker/Dockerfile -t fsharp docker
}

function dock() {
    docker run --rm -v "$PWD":"/root/FSharpTutorial" \
        -w "/root/FSharpTutorial" \
        -it fsharp $@
}

function install-paket() {
    mkdir .paket
    curl -L https://github.com/fsprojects/Paket/releases/download/5.194.0/paket.bootstrapper.exe -o .paket/paket.bootstrapper.exe
    mono .paket/paket.bootstrapper.exe
    echo ".paket/paket.exe" >> .gitignore
    echo ".packages" >> .gitignore
    mono .paket/paket.exe install
}

function install-mathnet-numerics() {
    mono nuget.exe update -self
    mono nuget.exe install MathNet.Numerics.FSharp -Pre -OutputDirectory packages
}


echo "$@"

$@
