#! /bin/bash

function build-docker() {
    docker build -f docker/Dockerfile -t fsharp docker
}

function dock() {
    docker run --rm -v "$PWD":"/root/FSharpTutorial" \
        -w "/root/FSharpTutorial" \
        -it fsharp $@
}

function install-paket() {
    dock bash scripts/install_paket.sh
}

function install-packages() {
    dock mono .paket/paket.exe install
}

echo "$@"

$@
